---
title: "practice_functions"
format: html
---

# Setup

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

```{r}
webpage <- rvest::read_html("https://www.pwrc.usgs.gov/BBL/Bander_Portal/login/speclist.php")

tbls <- rvest::html_nodes(webpage, "table") %>% 
    rvest::html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    janitor::clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))

head(species, 3)
```

```{r}
predator_survey <- read_csv("../data/Utqiagvik_predator_surveys.csv")
nest_data <- read_csv("../data/Utqiagvik_nest_data.csv")
egg_measures <- read_csv("../data/Utqiagvik_egg_measurements.csv")
```

```{r}
glimpse(nest_data)
colnames(nest_data)
unique(nest_data)
summary(nest_data)
```

```{r}
predator_comm_names <- left_join(predator_survey, species, by = c("species" = "alpha_code"))
```

```{r}
comm_name <- function(df, species){
  return_df <- left_join(df, species, by = c("species" = "alpha_code"))
  return(return_df)
}
```

```{r}
predator_survey_clean <- predator_survey %>%
  mutate( = na_if(O2, -99))
  comm_name(predator_survey, species)
nest_data_clean <-  comm_name(predator_survey, species)
egg_measures_clean <-   comm_name(predator_survey, species)

```

```{r}

```
